### ISSUE TITLE
Unable to install using Django 3.1.2 version.

### ISSUE THREAD

**Issue by RonelSutabinto** [umesh-krishna/django_serverside_datatable#1]
Unable to install using Django 3.1.2 version.
Do you have any requirements to make it compatible with Django 3.1.2?

 Message during installation of django_serverside_datatable:
 Requirement already satisfied: django-serverside-datatable in c:\users\ronel\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (0.1.0)

**Comment by lguariento** [comment]
I've had no issues in with my Django 3.1.5 regarding installation. I'm just not able to use it: #2 .

**Comment by umesh-krishna** [comment]
PR #4 fixed the issue
