### ISSUE TITLE
No module named 'django_serverside_datatable.django_serverside_datatable'

### ISSUE THREAD

**Issue by lguariento** [umesh-krishna/django_serverside_datatable#2]
I've installed django_serverside_datatable on my Django 3.1.5 / Python 3.7 project. Added to my 'INSTALLED_APPS' settings. Added to my views.py.

When I launch the makemigrations command I get this:

```
File "/home/hmsadm/virtualenv_fiddle/lib/python3.7/site-packages/django_serverside_datatable/views.py", line 3, in <module>
    from django_serverside_datatable.django_serverside_datatable import datatable
ModuleNotFoundError: No module named 'django_serverside_datatable.django_serverside_datatable'
```

**Comment by lguariento** [comment]
This is solved by changing line 3 of `.../site-packages/django_serverside_datatable/views.py` from

`from django_serverside_datatable.django_serverside_datatable import datatable`

to

`from django_serverside_datatable import datatable`

**Comment by svbfromnl** [comment]
Fixed by https://github.com/umesh-krishna/django_serverside_datatable/pull/4

You can close the issue now.
