### ISSUE TITLE
"MultiValueDictKeyError 'iDisplayStart'" and "TypeError - __init__() takes 1 positional argument but 2 were given errors"

### ISSUE THREAD

**Issue by lguariento** [umesh-krishna/django_serverside_datatable#3]
I've installed django_serverside_datatable and carefully followed the instructions. When pointing my browser to the page where my table is I get this:

```

Request Method: | GET
Django 3.1.5
TypeError
__init__() takes 1 positional argument but 2 were given
/home/hmsadm/virtualenv_fiddle/lib/python3.7/site-packages/django/core/handlers/base.py, line 181, in _get_response


```

When I point my browser to the /data directory directly I get this:

```
 File "/home/hmsadm/virtualenv_fiddle/lib/python3.7/site-packages/django/utils/datastructures.py", line 78, in __getitem__
    raise MultiValueDictKeyError(key)

Exception Type: MultiValueDictKeyError at /testdb/data/
Exception Value: 'iDisplayStart'
```

**Comment by lguariento** [comment]
PS: "For further customization of Datatable, you may refer the Datatable official documentation."

...which is... where?

**Comment by odoublewen** [comment]
@lguariento You closed this on the same day you opened it, so I guess you solved the problem.  Do you happen to recall how?

Seems to be some (lack of) interaction between datatables and this package.
