### ISSUE TITLE
queryset with parameter

### ISSUE THREAD

**Issue by Printns** [umesh-krishna/django_serverside_datatable#5]
Is it possible to use view.py with parameter like this:

from django_serverside_datatable.views import ServerSideDatatableView

class ItemListView(ServerSideDatatableView, id):
    queryset = models.Item.objects.get(id)
    columns = ['name', 'code', 'description']

**Comment by umesh-krishna** [comment]
`queryset` should hold a `QuerySet` object.
`objects.get()` returns a model Object. So, you should use `objects.filter()` instead.

**Comment by Printns** [comment]
ok, thanks!
So, the parameter (id) can be transferred through class declaration as usual?

**Comment by umesh-krishna** [comment]
@Printns You should probably use something like `queryset  = models.Item.objects.filter(id=id).all()`
