### ISSUE TITLE
Silent errors make debugging difficult

### ISSUE THREAD

**Issue by odoublewen** [umesh-krishna/django_serverside_datatable#6]
https://github.com/umesh-krishna/django_serverside_datatable/blob/0da2f9b5c6f1e5da2cc9aa1e521b1993533b7cb7/django_serverside_datatable/datatable.py#L65-L67

Nice package, but I think this section could be improved -- at the very least, log the error!

**Comment by umesh-krishna** [comment]
Thanks for the awesome review, @odoublewen. I'll soon fix all these issues

**Comment by umesh-krishna** [comment]
Fixed
