### ISSUE TITLE
iTotalRecords is not being set correctly

### ISSUE THREAD

**Issue by odoublewen** [umesh-krishna/django_serverside_datatable#7]
https://github.com/umesh-krishna/django_serverside_datatable/blob/0da2f9b5c6f1e5da2cc9aa1e521b1993533b7cb7/django_serverside_datatable/datatable.py#L27

`iTotalRecords` is being set to `cardinality` but it should be set to be `self.qs.count()`

I can provide a example if necessary, but I think this error should be evident and obvious to fix.

**Comment by umesh-krishna** [comment]
Fixed
