### ISSUE TITLE
sorting is always by `id` if no filtering 

### ISSUE THREAD

**Issue by odoublewen** [umesh-krishna/django_serverside_datatable#8]
https://github.com/umesh-krishna/django_serverside_datatable/blob/0da2f9b5c6f1e5da2cc9aa1e521b1993533b7cb7/django_serverside_datatable/datatable.py#L58

I think this would be fixed with the removal of `'id', ` in the `order_by()` method

**Comment by umesh-krishna** [comment]
Fixed
