### ISSUE TITLE
Custom Data Display

### ISSUE THREAD

**Issue by abedyngash** [umesh-krishna/django_serverside_datatable#9]
First things first, Good work! Impressive!
I'm just wondering however, Say I have a model with fields ```first_name``` and ```last_name```, And in the template I want to render something custom. For Instance ```first_name last_name```, or say I have a callable in my model ```get_full_name``` which returns ```f'{first_name} {last_name}'```. How would I render this in the template?

PS: I have maneuvered dealing with foreign key Fields, that is by using ```__``` in the columns list. For instance ```user__username```. I think this should be included in the documentation as well.

**Comment by umesh-krishna** [comment]
@abedyngash You can use Django's `annotate()` for this purpose.
Example:
(In your view definition)
`queryset = models.Person.objects.annotate(full_name=Concat('first_name', Value(' '), 'last_name')).all()`
`columns = ["full_name"]`

Thanks for your valuable feedback. I'll update the documentation soon.

**Comment by abedyngash** [comment]
Ooh. That's a brilliant workaround. I never thought the ```annotate```  would work in your case. That is perfect.

What if I wanted a counter though. Like ```forloop.counter``` in the AjaxResponse?

**Comment by umesh-krishna** [comment]
@abedyngash I didn't understand that. Can you please explain?

**Comment by abedyngash** [comment]
Okay, so normally, when you iterate over items in a django template, you can use the ```{{forloop.counter}}``` variable inside a ```{% for %}``` loop to get the counter of items.
It literally produces ```1,2,3....``` for all the items in the iterable object.

How do you achieve that with the Ajax response?

**Comment by umesh-krishna** [comment]
I think django template language doesn't work well inside ajax response handler function, because template is processed only at the beginning but ajax works after that.

**Comment by abedyngash** [comment]
Okay. I'll close this for the moment and try to think of a workaround.
